### ISSUE TITLE
Revert bibliography title styling

### ISSUE THREAD

**Issue by dstillman** [zotero/bib-web#271] opened 2021-06-21 20:38 UTC
After https://github.com/zotero/bib-web/commit/a2de2fb5068171fabd1eda5c6752819e6620d1b7, the display of the bibliography title changed.

Before:

![prod](https://user-images.githubusercontent.com/783082/122824707-03375600-d2af-11eb-9156-67ef03fe12a7.png)

After:

![staging](https://user-images.githubusercontent.com/783082/122824639-f0bd1c80-d2ae-11eb-93ba-6c38813e5a9a.png)

No longer centered, and a huge pencil icon

**Comment by tnajdek** [comment] 2021-06-21 20:58
Thanks, this and few more recent regressions in the UI (all selects, some inputs, especially in the manual editor) are caused by a2de2fb5. I'm planning on having it all fixed within next couple of days. The end goal is to remove dependency on `react-select`, bring over few minor features from Web Library (e.g. select options to move creator up/down) and eventually, possibly, extract few shared components to reduce code duplication between projects.

**Comment by tnajdek** [comment] 2021-06-24 17:21
Fixed in  67f2a111, b29443c3, 23a9d73f.

**Closed by tnajdek** 2021-06-24 17:21 UTC
